### ISSUE TITLE
Clarification: Address and Value Behavior in ex02

### ISSUE THREAD

**Issue by veloxity343** [tblaase/CPP-Module-01#1]
<p>
The purpose of <em>ex02</em> is to illustrate the difference between pointers and references. However, there seems to be some confusion in the expected behavior regarding the memory addresses and values displayed. Specifically:
</p>
<ul>
  <li>The memory address of the <code>string</code> pointer (<code>stringPTR</code>) should not match that of the <code>string</code> or the reference (<code>stringREF</code>).</li>
  <li>The "value pointed to by <code>stringPTR</code>" should reflect the address of <code>string</code>, not the string's content itself.</li>
</ul>

<p>Below is an example implementation based on my understanding, working on your own implementation:</p>

<pre>
<code>
int main(void)
{
    std::string string = "HI THIS IS BRAIN";
    std::string *stringPTR = &string;
    std::string &stringREF = string;

    std::cout << "Address of string:\t" << &string << std::endl;
    std::cout << "Address of stringPTR:\t" << &stringPTR << std::endl; // note we print the address of our pointer, which calls its own address
    std::cout << "Address of stringREF:\t" << &stringREF << std::endl;

    std::cout << std::endl;

    std::cout << "Value of string:\t\t" << string << std::endl;
    std::cout << "Value pointed to by stringPTR:\t" << stringPTR << std::endl; // note we print the value of what our pointer points to
    std::cout << "Value of stringREF:\t\t" << stringREF << std::endl;

    return (EXIT_SUCCESS);
}
</code>
</pre>

<p>Expected output:</p>

<pre>
<code>
./brain
Address of string:      0x16d3872c0
Address of stringPTR:   0x16d3872b8
Address of stringREF:   0x16d3872c0

Value of string:                HI THIS IS BRAIN
Value pointed to by stringPTR:  0x16d3872c0
Value of stringREF:             HI THIS IS BRAIN
</code>
</pre>

All that is to say, a minor detail that struck me as odd when referring to your implementation. Hope I managed to clear it up. Big thanks to you for making this repo publicly available and helping me with my understanding and approach in this 42 project!

**Comment by tblaase** [comment]
Thanks for pointing that out, I somehow missed that.
